workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: ffelicissimo/ffelicissimo
        environment:
          GERU_PASS: $GERU_PASS
      - image: ffelicissimo/credtodos:latest
        environment:
          GERU_PASSWORD: $GERU_PASS

 
deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            docker push ffelicissimo/credtodos:latest master        
