machine:
  timezone:
    America/Sao_Paulo
  services:
    - docker
dependencies:
  pre:
    - docker version
    - docker info
  override:
    - docker info
    - docker build --rm=false -t ffelicissimo/credtodos .
test:
  override:
   - echo "test"
   - docker run -d -p 80:80 --name=credtodos credtodos/credtodos ; sleep 5 
   - curl -H "Authorization: Token $GERU_PASS" http://localhost/

version: 2
jobs:
  build:
    branches:
      only:
        - test-build-initial
        - build-*
    docker:
      - image: ffelicissimo/credtodos
    steps:
      - checkout
      - run:
          name: credtodosapi
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date 
          
deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - docker push ffelicissimo/credtodos